// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goFrameMall/internal/logic/position"
	_ "goFrameMall/internal/logic/rotation"
)
