
# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name:     "goFrameMall"
    arch:     "arm64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link:            "mysql:root:12345678@tcp(127.0.0.1:3306)/goFrameMall?loc=Local"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true